---
# tasks file for setup_cri-o
- name: Download crio installer
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/cri-o/cri-o/main/scripts/get"
    dest: /tmp/getcrio.sh
    mode: '0750'
    force: true
- name: Run the crio installer
  ansible.builtin.shell: /tmp/getcrio.sh
  args:
    executable: /bin/bash
  register: _result
